export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_ERROR = "ADMIN_LOGIN_ERROR";

export const ELIGIBILITY_REQUEST = "ELIGIBILITY_REQUEST";
export const ELIGIBILITY_SUCCESS = "ELIGIBILITY_SUCCESS";
export const ELIGIBILITY_ERROR = "ELIGIBILITY_ERROR";